name: Generate Snake

# Controls when the action will run
on:
  # Schedule to run every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows the action to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use the latest stable Ubuntu version
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake GIF and SVG
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rahul-sharma-alx  # Replace with your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build (useful for debugging)
      - name: Check build status
        run: git status

      # Commit and push the changes
      - name: Commit and Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy the output branch to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: set output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
